added a LOCphy file + 1st impl
sse-labs/fachproject-metrics-framework pull request #32
Opened 2021-12-16 13:04 UTC by SandraSunny02

2022-01-20 13:40 UTC, skyfly18 commented
Quellcode der Test Jar Fehlt.
Bitte die Test erweitern auf Jar Files von Maven Central.

2022-01-20 17:43 UTC, skyfly18 requested changes

2022-01-20 17:43 UTC, skyfly18 commented on src/main/scala/impl/group4/LOCphyAnalysis.scala
> +      if (table.size>1) List(MetricValue(m.fullyQualifiedSignature, analysisName, table.last.lineNumber - table.head.lineNumber))
Was ist wenn lineNumberTable leer ist? Warum wird keine Warnung ausgeben?

2022-01-20 17:43 UTC, skyfly18 commented on src/test/scala/impl/group4/LOCphyAnalysisTest.scala
> +  }
Wo ist der Fall, wenn es keine LineNumberTable ob wirklich nichts dazu in metricResult steht.

2022-01-22 13:14 UTC, VidRuntimes requested changes
Jar source code wäre gut um die Tests nachvollziehen zu können + Tests von jars die ihr nicht selber geschrieben habt

2022-01-24 20:07 UTC, skyfly18 approved these changes

2022-01-24 20:07 UTC, VidRuntimes approved these changes

2022-01-24 20:09 UTC, merged