Metric TCC merge request
sse-labs/fachproject-metrics-framework pull request #46
Opened 2022-01-11 16:18 UTC by MehdiHa96

This will calculate the TCC of each class in the project according to the original formal definition by Kang & Bieman in the following paper: 

L. Ott; J.M. Biemann; B. Kang; B. Mehra,
[Developing Measures of Class Cohesion for Object-Oriented Software,](https://www.cs.colostate.edu/~bieman/Pubs/aowsm95.pdf)
June 1995

If you have any questions, feel free to post it under this discussion. (For urgent cases, telegram: [@MehdiHa96 ](https://t.me/Mehdi_Hassanpour))

_Hint: **Make sure to pass the right CLI argument to the application**_

closes #19

2022-01-19 22:05 UTC, Helmi97 requested changes
Das gleiche Problem von LCC passiert hier auch 
[Kommentar](https://github.com/sse-labs/fachproject-metrics-framework/pull/47#pullrequestreview-857408963)

2022-01-19 22:12 UTC, MehdiHa96 commented
Diese Methoden sind weder direkt noch indirekt miteinander verbunden. Die Definition findest du gerne im oben genannten Paper :)

2022-01-23 16:47 UTC, skyfly18 requested changes
Gleiche Anmerkungen wie bei LCC.

2022-01-23 16:47 UTC, skyfly18 commented on src/test/scala/testTCC/TCCAnalysisTest.scala
> +
Tests von anderen Jars files wären noch schön

2022-01-23 18:25 UTC, skyfly18 requested changes
Das  gleiche wie bei LCC

2022-01-24 20:08 UTC, skyfly18 approved these changes

2022-01-24 20:33 UTC, merged