Metric LOCpro - Merge Request
sse-labs/fachproject-metrics-framework pull request #48
Opened 2022-01-11 16:24 UTC by MehdiHa96

If you have any questions, feel free to post it under this discussion.

_Hint: **Make sure to pass the right CLI argument to the application**_

closes #5

2022-01-19 20:50 UTC, Helmi97 approved these changes

2022-01-19 20:50 UTC, Helmi97 commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +  /** calculates all class methods, from all line number table get each method body lines, then add 1 as method itself*/
Die Beschreibung ist nicht klar

2022-01-19 20:50 UTC, Helmi97 commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +    var lineCounter = 0
Braucht man diese variable?

2022-01-19 21:33 UTC, Helmi97 requested changes
Falsche Ergebnisse bei void methods

2022-01-19 21:33 UTC, Helmi97 commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +              lineCounter = lineCounter + m.body.get.lineNumberTable.get.lineNumbers.size + 1
bei void Methoden gibt es eine extra Return Zeile die man nur im Bytecode sehen kann, deswegen braucht man kein +1

2022-01-20 13:34 UTC, vickymeitong commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +              lineCounter = lineCounter + m.body.get.lineNumberTable.get.lineNumbers.size + 1
Hab über void methode das Code geändert, bitte noch testen

2022-01-23 16:56 UTC, VidRuntimes reviewed
Source code der eigenen jars wäre ganz praktisch, aber ist sonst gut auch ohne Kommentare nachzuvollziehen

2022-01-23 16:56 UTC, VidRuntimes commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +    var lineCounter = 0
Die log.info sollte vll auch entfernt werden

2022-01-23 17:01 UTC, skyfly18 requested changes
Wie bei LCC und TCC fehlt der Code der Test Jars.

2022-01-23 17:01 UTC, skyfly18 commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +            if (m.body.exists(_.lineNumberTable.nonEmpty)) {
Eine Info wäre schön wenn linetable nicht verfügbare ist.

2022-01-23 17:03 UTC, ksuguss commented on src/main/scala/impl/group3/LOCproAnalysis.scala
> +    log.info("Please implement the LOCpro metric here")
Danke für den hilfreichen Reminder! Wir werden die Jars hochladen :)

2022-01-24 14:50 UTC, ksuguss approved these changes

2022-01-24 15:12 UTC, skyfly18 approved these changes

2022-01-24 15:44 UTC, merged