Metric/cc
sse-labs/fachproject-metrics-framework pull request #61
Opened 2022-01-19 22:13 UTC by Helmi97

2022-01-20 11:21 UTC, skyfly18 requested changes
Mehr Tests von verschiedne Jar Files.

2022-01-20 11:21 UTC, skyfly18 commented on src/test/scala/impl/group4/MCCCAnalysisTest.scala
> +      val fileToTest = new File(getClass.getResource("/group4/maven-jar-sample-1.0-SNAPSHOT.jar").getPath)
Was ist mit anderen jar Files? Ihr guck hier nur ob eure eigene Jar File richtig berechnet wird.
Nimmt mindestes zwei Jar Files von Maven Central und schreibt zu diesen auch noch gute Tests.

2022-01-20 11:21 UTC, skyfly18 commented on src/main/scala/impl/group4/MCCCAnalysis.scala
> +    if (project.isProjectType(m.classFile.thisType) && m.body.isDefined) {
Warum keine CustomOptions? Ihr könnt als optional E, N und P ausgeben.

2022-01-20 12:28 UTC, skyfly18 commented
Der Quellcode eures Beispiel Jar File wäre schön zu haben um die Funktionalität eurer Test zu bewerten.

2022-01-22 13:13 UTC, VidRuntimes requested changes
Jar source code wäre gut um die Tests nachvollziehen zu können + Tests von jars die ihr nicht selber geschrieben habt

2022-01-24 16:33 UTC, VidRuntimes approved these changes

2022-01-24 18:33 UTC, skyfly18 approved these changes

2022-01-24 18:46 UTC, closed without merging