Metric/lloc
sse-labs/fachproject-metrics-framework pull request #62
Opened 2022-01-20 12:12 UTC by Helmi97

2022-01-20 13:39 UTC, skyfly18 commented
Quellcode der Test Jar Fehlt.
Bitte die Test erweitern auf Jar Files von Maven Central.

2022-01-22 12:06 UTC, skyfly18 requested changes
Mehr Tests

2022-01-22 13:13 UTC, VidRuntimes requested changes
Jar source code wäre gut um die Tests nachvollziehen zu können + Tests von jars die ihr nicht selber geschrieben habt

2022-01-23 23:32 UTC, VidRuntimes approved these changes

2022-01-24 18:57 UTC, skyfly18 approved these changes

2022-01-24 22:24 UTC, SandraSunny02 commented
the base branch is protected?? 
can't resolve conflict

2022-01-24 23:16 UTC, closed without merging

2022-01-24 23:16 UTC, SandraSunny02 commented
see new Branch LLOC to resolve this conflict