Metric/dac
sse-labs/fachproject-metrics-framework pull request #63
Opened 2022-01-20 12:50 UTC by Helmi97

2022-01-20 13:39 UTC, skyfly18 commented
Quellcode der Test Jar Fehlt.
Bitte die Test erweitern auf Jar Files von Maven Central.

2022-01-20 18:51 UTC, skyfly18 requested changes
Es fehlt GANZ VIEL!!!
Laut euren Paper müsst ihr die Klassentypen auch in den Methoden zählen und nicht nur in den FIELDS.
Als customOption könnt ihr auch die Anzahl der Klassentypen zählen und ausgeben.

2022-01-20 18:51 UTC, skyfly18 commented on src/main/scala/impl/group4/DACAnalysis.scala
> +      if (f.fieldType.isReferenceType & !classes.contains(f.asField.fieldType.toString)) {
Was ist mit denn Methoden?

2022-01-20 18:51 UTC, skyfly18 commented on src/main/scala/impl/group4/DACAnalysis.scala
> +    List(MetricValue(classFile.fqn, "class.dac", metric))
Wie oft wird eine Klasse als Datentype verwendet?
Hier kann man noch viel mit customoptionen machen.

2022-01-22 13:13 UTC, VidRuntimes requested changes
Jar source code wäre gut um die Tests nachvollziehen zu können + Tests von jars die ihr nicht selber geschrieben habt

2022-01-24 19:38 UTC, skyfly18 requested changes
Die Metrik zählt nicht richtig

2022-01-24 19:38 UTC, skyfly18 commented on src/test/scala/impl/group4/DACAnalysisTest.scala
> +      assert(metricResult1.metricValues.exists(value => value.entityIdent.equals("com/group4/sample/DACAnalysisTest2") && value.metricValue == 1.0))
Warum steht ihr eine 1. Laut source code möchte hier eine 0 stehen.

2022-01-24 21:16 UTC, Helmi97 commented on src/test/scala/impl/group4/DACAnalysisTest.scala
> +      assert(metricResult1.metricValues.exists(value => value.entityIdent.equals("com/group4/sample/DACAnalysisTest2") && value.metricValue == 1.0))
Die Klasse wird im default constructor Methode definiert deswegen hat jede Klasse dac>=1

2022-01-24 21:25 UTC, skyfly18 commented on src/test/scala/impl/group4/DACAnalysisTest.scala
> +      assert(metricResult1.metricValues.exists(value => value.entityIdent.equals("com/group4/sample/DACAnalysisTest2") && value.metricValue == 1.0))
Trotzdem zählt ihr dann falsch. Entfernt das ihr denn constructor mitzählt. Denn Dac soll ja ausdrücken wie oft wie viele Variablen auf Klassen zeigen.

2022-01-25 10:28 UTC, johannesduesing commented
Hallo zusammen,

was ist der aktuelle Status hier?  Wenn dieser PR zusammen mit #64 noch Teil der Abgabe werden soll dann bitte sobald wie möglich mergen, ich würde gerne den Master-Merge vorbereiten und da das Review starten. Wenn das heute zeitlich nichts mehr wird dann können wir diese Metriken nicht mit in den Release nehmen und müssten die dann nachträglich mergen.

2022-01-25 13:54 UTC, skyfly18 requested changes
Ich bekomme beim testen noch ein merkwürdiger Fehler.
Beim code:

public class work2 {

    public  void endework(String work)
    {
        System.out.println(work);
    }
}

Bekomme ich DAC 1 angezeigt.

2022-01-25 15:42 UTC, skyfly18 approved these changes

2022-01-25 16:08 UTC, VidRuntimes approved these changes

2022-01-25 16:09 UTC, merged