Metric/rfc
sse-labs/fachproject-metrics-framework pull request #64
Opened 2022-01-20 12:50 UTC by Helmi97

2022-01-20 13:39 UTC, skyfly18 commented
Quellcode der Test Jar Fehlt.
Bitte die Test erweitern auf Jar Files von Maven Central.

2022-01-22 12:06 UTC, skyfly18 requested changes
Mehr Tests

2022-01-22 13:12 UTC, VidRuntimes requested changes
Jar source code wäre gut um die Tests nachvollziehen zu können + Tests von jars die ihr nicht selber geschrieben habt

2022-01-22 13:49 UTC, VidRuntimes commented on src/main/scala/impl/group4/RFCAnalysis.scala
> +        if(i!=null) if (i.isMethodInvocationInstruction) rfc = rfc + 1
Ich glaube hier sollten Methoden die schon von der Klasse aufgerufen werden nicht nocheinmal gezählt werden.
Siehe Seite 13 aus dem ersten Paper
![firefox_7xXSJNwnAu](https://user-images.githubusercontent.com/71559471/150640823-4eb57c63-fd08-45d5-93ea-2afbd1398834.png)

2022-01-24 19:16 UTC, skyfly18 requested changes
Beim eigen Test jar, der erste Test sind 3 Methoden im source aber die Metrik zählt nur 2.
Damit zählt die Metrik nicht korrekt

2022-01-24 21:11 UTC, Helmi97 commented
> 

In der erste Test sind 3 private Methoden im source aber die Metrik zählt 2 statt 0 wegen dem _default constructor_: `com.group4.sample.RFCAnalysisTest1{ void <init>() }` + `java.lang.Object{ void <init>() }`

2022-01-24 21:18 UTC, skyfly18 commented
Wer sagt das private Methoden nicht mitgezählt werden sollen. RFC zählt ja die vorhanden Methoden einer Klasse plus die aufgerufenden Methoden.

2022-01-25 00:07 UTC, Helmi97 commented
> Wer sagt das private Methoden nicht mitgezählt werden sollen. RFC zählt ja die vorhanden Methoden einer Klasse plus die aufgerufenden Methoden.

In der Definition geht es um Methoden die aufgerufen können wenn ein Objekt der Klasse ein Message bekommt
![image](https://user-images.githubusercontent.com/22029737/150885747-1953463a-9b0a-4109-9f63-67cf93ee5bb5.png)

[When object A wants object B to perform one of B's methods, object A sends a message to object B.](https://www.cis.upenn.edu/~bcpierce/courses/629/papers/Java-tutorial/java/objects/messages.html). Object B kann nur public Methoden von Object A erreichen, deswegen enthält die Response Set nur Public Methoden und die Methoden die sie aufrufen.

2022-01-25 09:02 UTC, skyfly18 commented
Ri kann nur public Methoden sein aber M ist sind alle methoden in der Klasse. Da steht nicht das M nur public Methoden enthält.

2022-01-25 14:22 UTC, skyfly18 commented
@VidRuntimes hat schon erwähnt das Methoden nicht mehrmals gezählt werden sollen

2022-01-25 14:23 UTC, skyfly18 commented on src/main/scala/impl/group4/RFCAnalysis.scala
> +        if(i!=null) if (i.isMethodInvocationInstruction) rfc = rfc + 1
Immer noch aktuall

2022-01-25 14:24 UTC, skyfly18 requested changes
Wie schon erwähnt

2022-01-25 15:35 UTC, skyfly18 approved these changes
Sollte nun alles in Ordnung sein

2022-01-25 16:09 UTC, VidRuntimes approved these changes

2022-01-25 16:09 UTC, merged